const searchTypes = {
  UPDATE_QUERY: 'UPDATE_QUERY',
  SUBMIT_QUERY: 'SUBMIT_QUERY',
  QUERY_SUBMIT_REQUEST: 'QUERY_SUBMIT_REQUEST',
  QUERY_SUBMIT_SUCCESS: 'QUERY_SUBMIT_SUCCESS',
  QUERY_SUBMIT_ERROR: 'QUERY_SUBMIT_ERROR',
};

export default searchTypes;
