const searchTypes = {
  UPDATE_PDBS: 'UPDATE_PDBS',
  UPDATE_QUERY: 'UPDATE_QUERY',
  UPLOAD_FILE: 'UPLOAD_FILE',
  REMOVE_FILE: 'REMOVE_FILE',
  QUERY_SUBMIT_REQUEST: 'QUERY_SUBMIT_REQUEST',
  QUERY_SUBMIT_SUCCESS: 'QUERY_SUBMIT_SUCCESS',
  QUERY_SUBMIT_ERROR: 'QUERY_SUBMIT_ERROR',
  UPDATE_RESULTS: 'UPDATE_RESULTS',
};

export default searchTypes;
